name: 'Acceptance Test Project Template'
on: 
  push:
    tags:
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100'
          source-url: https://nuget.pkg.github.com/hi-digital-solutions/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create Package
        run: dotnet pack working/ --configuration Release

      - name: Upload Package
        if: startsWith(github.ref, 'refs/tags/')
        run: dotnet nuget push working/bin/Release/*.nupkg --skip-duplicate --no-symbols true